import {mkdtemp,readFile,rm} from "node:fs/promises";import path from "node:path";import os from "node:os";import {expect,it} from "vitest";
import {defaultClip,defaultTransform,secondsToTicks,type AnimationDocument} from "@mcp-video-studio/contracts";import {ProjectStore} from "@mcp-video-studio/core";import {importMedia,loadConfig,runChecked} from "@mcp-video-studio/media";import {renderAnimation} from "@mcp-video-studio/animation";import {renderSequence} from "@mcp-video-studio/renderer";
const integration=process.env.RUN_BROWSER_INTEGRATION==="1"&&process.env.RUN_FFMPEG_INTEGRATION==="1"?it:it.skip;
integration("animation clips retain exact trim, split, speed, effect and transition pixels like equivalent managed media",async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),"studio-animation-clips-"));try{
  const store=await ProjectStore.create(path.join(root,"project"),"Animation clips"),config=loadConfig({...process.env,VIDEO_STUDIO_DATA_DIR:root,VIDEO_STUDIO_SCRATCH_DIR:path.join(root,"scratch")}),fps={numerator:10,denominator:1};
  await store.replace(0,project=>{project.settings.fps=fps;project.settings.raster={width:160,height:90};},{sequences:[],tracks:[],clips:[],media:[],animations:[],generatedArtifacts:[]});
  const document:AnimationDocument={id:"scene",name:"Editable scene",mode:"declarative",seed:21,canvas:{width:160,height:90,background:"transparent"},durationTick:secondsToTicks(4),nodes:[{id:"box",name:"Box",type:"rect",properties:{width:50,height:30,fill:"#ff0000"},transform:{...defaultTransform(),position:[30,45]}}],operations:[{id:"move",targetId:"box",type:"transform",startTick:0,durationTick:secondsToTicks(4),easing:"linear",parameters:{to:{position:[130,45]}}},{id:"color",targetId:"box",type:"property",startTick:0,durationTick:secondsToTicks(4),easing:"linear",parameters:{property:"fill",from:"#ff0000",to:"#0000ff"}}]};
  const project=await store.read(),sequence=project.sequences[0]!,track=sequence.tracks[0]!,first=defaultClip(track.id,{type:"animation",animationId:document.id},"Fast animation",secondsToTicks(1)),second=defaultClip(track.id,{type:"animation",animationId:document.id},"Slow animation",secondsToTicks(1));
  first.sourceInTick=secondsToTicks(.5);first.playbackRate={numerator:2,denominator:1};first.effects=[{id:"brightness",type:"brightness",version:1,enabled:true,parameters:{value:.1}}];second.startTick=secondsToTicks(1);second.sourceInTick=secondsToTicks(.5);second.playbackRate={numerator:1,denominator:2};second.transform.rotation=15;second.transform.scale=[.8,.8];
  await store.mutate(1,[{type:"animation.set",animation:document},{type:"clip.add",sequenceId:sequence.id,clip:first,mode:"overwrite"},{type:"clip.add",sequenceId:sequence.id,clip:second,mode:"overwrite"},{type:"transition.add",sequenceId:sequence.id,transition:{id:"dissolve",sequenceId:sequence.id,fromClipId:first.id,toClipId:second.id,type:"crossfade",durationTick:secondsToTicks(.4),parameters:{}}}]);
  const raw=async(file:string)=>{const decoded=file+".rgba";await runChecked(config.ffmpegPath,["-hide_banner","-y","-i",file,"-map","0:v:0","-pix_fmt","rgba","-f","rawvideo",decoded]);return readFile(decoded);};
  const render=async(name:string,ranges=0)=>{const file=path.join(root,name+".mkv");await renderSequence(store,config,{sequenceId:sequence.id,presetId:"archive-ffv1",outputPath:file,videoRangeFrames:ranges});return raw(file);};
  const before=await render("before");expect(before.length).toBe(20*160*90*4);
  await store.mutate(2,[{type:"clip.split",sequenceId:sequence.id,clipId:first.id,atTick:secondsToTicks(.5),rightClipId:"split-right"}]);
  const split=await render("split");if(!split.equals(before))console.log("SPLIT_DIAGNOSTIC",JSON.stringify({clips:(await store.read()).sequences[0]!.clips,transitions:(await store.read()).sequences[0]!.transitions,frames:Array.from({length:20},(_,frame)=>({frame,equal:split.subarray(frame*160*90*4,(frame+1)*160*90*4).equals(before.subarray(frame*160*90*4,(frame+1)*160*90*4))}))}));expect(split.equals(before)).toBe(true);expect((await store.read()).sequences[0]!.transitions[0]!.fromClipId).toBe("split-right");
  await store.mutate(3,[{type:"clip.trim",sequenceId:sequence.id,clipId:second.id,edge:"out",tick:secondsToTicks(1.8),ripple:false}]);const trimmed=await render("trimmed");expect(trimmed.length).toBe(18*160*90*4);expect(trimmed.equals(before.subarray(0,trimmed.length))).toBe(true);
  const source=path.join(root,"source.mkv");await renderAnimation(document,config,{fps,outputPath:source});const imported=await importMedia(store,source,"managed",4,config);
  await store.replace(5,p=>{for(const clip of p.sequences[0]!.clips)if(clip.source.type==="animation")clip.source={type:"media",mediaId:imported.asset.media.id};},{sequences:[sequence.id],tracks:[track.id],clips:[first.id,second.id,"split-right"],media:[imported.asset.media.id],animations:[],generatedArtifacts:[]});
  const equivalent=await render("equivalent-media",5);
  if(!equivalent.equals(trimmed)){const frames=Array.from({length:18},(_,frame)=>{let differing=0,maxDelta=0;for(let offset=frame*160*90*4;offset<(frame+1)*160*90*4;offset++){const delta=Math.abs((equivalent[offset]??0)-(trimmed[offset]??0));if(delta)differing++;maxDelta=Math.max(maxDelta,delta);}return{frame,differing,maxDelta};});console.log("ANIMATION_MEDIA_PARITY",JSON.stringify({frames,equivalentBytes:equivalent.length,trimmedBytes:trimmed.length,equivalentFirst:[...equivalent.subarray(0,16)],trimmedFirst:[...trimmed.subarray(0,16)],probe:imported.asset.media.probe}));}
  expect(equivalent.equals(trimmed)).toBe(true);
 }finally{await rm(root,{recursive:true,force:true});}
},120000);
