import {mkdtemp,rm,copyFile} from "node:fs/promises";import {existsSync} from "node:fs";import path from "node:path";import os from "node:os";import {expect,it} from "vitest";import {chromium} from "patchright";import axe from "axe-core";
import {Client} from "@modelcontextprotocol/client";import {StdioClientTransport} from "@modelcontextprotocol/client/stdio";import {ProjectStore} from "@mcp-video-studio/core";
const integration=process.env.RUN_BROWSER_INTEGRATION==="1"?it:it.skip;
integration("browser imports a portable font and ASS, edits caption finishing and exports a reviewed MCP sidecar",async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),"studio-caption-finishing-")),store=await ProjectStore.create(path.join(root,"projects","captions"),"Caption finishing"),client=new Client({name:"caption-finishing",version:"1"},{versionNegotiation:{mode:"auto"}});
 const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve("dist/index.js"),"--stdio"],env:{...Object.fromEntries(Object.entries(process.env).filter((p):p is[string,string]=>typeof p[1]==="string")),VIDEO_STUDIO_DATA_DIR:root,VIDEO_STUDIO_GATEWAY_PORT:"0"},stderr:"pipe"});const browser=await chromium.launch({headless:true});
 try{
  await store.replace(0,project=>{project.settings.raster={width:320,height:180};project.settings.fps={numerator:10,denominator:1};},{sequences:[],tracks:[],clips:[],media:[],animations:[],generatedArtifacts:[]});
  const system=[path.join(process.env.WINDIR??"C:\\Windows","Fonts","arial.ttf"),"/System/Library/Fonts/Supplemental/Arial.ttf","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"].find(existsSync);expect(system).toBeDefined();const font=path.join(root,"Reviewed.ttf");await copyFile(system!,font);
  await client.connect(transport);const response=await client.callTool({name:"open_studio",arguments:{projectPath:store.root}}),url=(response.structuredContent as{studioUrl:string}).studioUrl;const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(15000);await page.goto(url);await page.getByText("Project loaded",{exact:true}).waitFor();
  await page.getByLabel("Absolute media file path").fill(font);await page.getByRole("button",{name:"Import media",exact:true}).click();await page.waitForFunction(()=>document.body.textContent?.includes("rev 2"));await rm(font);
  await page.getByRole("button",{name:"Editing workflows",exact:true}).click();await page.getByLabel("Caption format").selectOption("ass");await page.getByLabel("Caption source").fill("[Script Info]\nScriptType: v4.00+\nPlayResX: 320\nPlayResY: 180\n[V4+ Styles]\nFormat: Name,Fontname,Fontsize,PrimaryColour,OutlineColour,BackColour,BorderStyle,Outline,Shadow,Alignment\nStyle: Main,Arial,24,&H00FFFFFF,&H00000000,&H00000000,1,1,1,2\n[Events]\nFormat: Layer,Start,End,Style,Text\nDialogue: 0,0:00:00.00,0:00:01.00,Main,Imported caption\n");await page.getByRole("button",{name:"Import captions",exact:true}).click();await page.waitForFunction(()=>document.body.textContent?.includes("rev 3"));await page.getByRole("button",{name:"Close editing workflows"}).click();await page.locator(".caption-block").first().press("Enter");
  await page.getByLabel("Caption font",{exact:true}).selectOption({label:"Reviewed.ttf"});await page.getByText("Saved revision 4",{exact:true}).waitFor();await page.getByLabel("Outline width",{exact:true}).fill("2");await page.getByLabel("Outline width",{exact:true}).press("Tab");await page.getByText("Saved revision 5",{exact:true}).waitFor();await page.getByLabel("Left margin",{exact:true}).fill("24");await page.getByLabel("Left margin",{exact:true}).press("Tab");await page.getByText("Saved revision 6",{exact:true}).waitFor();await page.getByLabel("Caption text",{exact:true}).fill("Reviewed caption");await page.getByLabel("Caption text",{exact:true}).press("Tab");await page.getByText("Saved revision 7",{exact:true}).waitFor();
  const project=await store.read(),cue=project.sequences[0]!.captions[0]!;expect(cue).toMatchObject({text:"Reviewed caption",style:{fontMediaId:project.media[0]!.id,outlineWidth:2,marginLeft:24}});const exported=await client.callTool({name:"export_captions",arguments:{projectPath:store.root,sequenceId:project.sequences[0]!.id,format:"ass"}});expect(exported.isError).not.toBe(true);expect((exported.structuredContent as{text:string;mimeType:string})).toMatchObject({mimeType:"text/x-ssa"});expect((exported.structuredContent as{text:string}).text).toContain("Reviewed caption");
  await page.reload();await page.getByText("Project loaded",{exact:true}).waitFor();await page.locator(".caption-block").first().press("Enter");expect(await page.getByLabel("Caption font",{exact:true}).locator("option:checked").textContent()).toBe("Reviewed.ttf");expect(await page.getByLabel("Outline width",{exact:true}).inputValue()).toBe("2");
  await page.evaluate(axe.source,undefined,false);const accessibility=await page.evaluate(async()=>await(window as unknown as{axe:typeof axe}).axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}}),undefined,false);expect(accessibility.violations.map(item=>({id:item.id,nodes:item.nodes.map(node=>node.target)}))).toEqual([]);
 }finally{await browser.close();await client.close();await rm(root,{recursive:true,force:true});}
},60000);
