import {mkdtemp,rm,readdir} from "node:fs/promises";import os from "node:os";import path from "node:path";import {expect,it} from "vitest";
import {ProjectStore} from "@mcp-video-studio/core";import {parseCaptions} from "@mcp-video-studio/contracts";import {loadConfig} from "@mcp-video-studio/media";import {measureCaptionLayout,renderSequence,runQc} from "@mcp-video-studio/renderer";
const integration=process.env.RUN_FFMPEG_INTEGRATION==="1"?it:it.skip;
integration("actual export font metrics identify clipping and safe margins, deduplicate text, and connect QC to its caption",async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),"studio-caption-layout-"));try{
  const store=await ProjectStore.create(path.join(root,"project"),"Caption layout"),config=loadConfig({...process.env,VIDEO_STUDIO_DATA_DIR:root,VIDEO_STUDIO_SCRATCH_DIR:path.join(root,"scratch")});
  await store.replace(0,project=>{project.settings.raster={width:320,height:180};project.settings.fps={numerator:10,denominator:1};},{sequences:[],tracks:[],clips:[],media:[],animations:[],generatedArtifacts:[]});
  let project=await store.read(),sequence=project.sequences[0]!,track=sequence.tracks.find(track=>track.type==="caption")!;
  const captions=parseCaptions("1\n00:00:00,000 --> 00:00:00,500\nAn intentionally oversized caption\n\n2\n00:00:00,500 --> 00:00:01,000\nTwo\nlines\n","srt",track.id,project.settings.fps,{fontFamily:"sans-serif",fontSize:24,color:"#ffffff",background:"#00000000",position:"top",align:"left",marginLeft:20,marginVertical:20,outlineWidth:2,shadowOffset:1});
  await store.mutate(1,captions.map(caption=>({type:"caption.add" as const,sequenceId:sequence.id,caption})));project=await store.read();sequence=project.sequences[0]!;
  const result=await measureCaptionLayout(store,project,sequence,config);expect(result.complete).toBe(true);expect(result.measurements).toHaveLength(2);expect(result.measurements[0]).toMatchObject({captionId:captions[0]!.id,overflow:true,outsideSafeArea:true,bounds:{left:18,top:18}});expect(result.measurements[0]!.textWidth).toBeGreaterThan(320);expect(result.measurements[1]!.textHeight).toBeGreaterThan(24);expect(result.measurements[1]).toMatchObject({overflow:false,outsideSafeArea:false});
  const output=path.join(root,"captions.mkv");await renderSequence(store,config,{sequenceId:sequence.id,presetId:"archive-ffv1",outputPath:output,videoRangeFrames:0});const qc=await runQc(store,sequence.id,output,config) as {passed:boolean;checks:Array<{checkId?:string;status:string;captionIds?:string[];startTick?:number}>};expect(qc.passed).toBe(false);expect(qc.checks.find(check=>check.checkId==="caption.overflow")).toMatchObject({status:"FAIL",captionIds:[captions[0]!.id],startTick:0});
  await store.mutate(2,[{type:"caption.update",sequenceId:sequence.id,captionId:captions[0]!.id,patch:{text:"Two\nlines",style:{...captions[0]!.style,marginLeft:0}}}]);project=await store.read();sequence=project.sequences[0]!;const adjusted=await measureCaptionLayout(store,project,sequence,config);expect(adjusted.measurements[0]!.textWidth).toBe(adjusted.measurements[1]!.textWidth);expect(adjusted.measurements[0]!.outsideSafeArea).toBe(true);expect(adjusted.measurements[0]!.overflow).toBe(true);
  expect((await readdir(config.scratchDir)).filter(name=>name.startsWith("caption-layout-"))).toEqual([]);
  const abort=new AbortController();abort.abort();await expect(measureCaptionLayout(store,project,sequence,config,abort.signal)).rejects.toThrow();expect((await readdir(config.scratchDir)).filter(name=>name.startsWith("caption-layout-"))).toEqual([]);
 }finally{await rm(root,{recursive:true,force:true});}
},60000);
