import {mkdtemp,readFile,rm,copyFile,writeFile} from "node:fs/promises";import {existsSync} from "node:fs";import path from "node:path";import os from "node:os";import {expect,it} from "vitest";
import {ProjectStore,sequenceDependencies} from "@mcp-video-studio/core";import {parseCaptions} from "@mcp-video-studio/contracts";import {importMedia,loadConfig,probeMedia,runChecked} from "@mcp-video-studio/media";import {renderSequence} from "@mcp-video-studio/renderer";
it("rejects malformed and unsupported font directories before decoder execution",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"studio-bad-font-"));try{const font=path.join(root,"bad.ttf");await writeFile(font,Buffer.alloc(100));await expect(probeMedia(font,loadConfig({...process.env,VIDEO_STUDIO_FFPROBE_PATH:"missing-probe"}))).rejects.toThrow(/standalone/);const header=Buffer.alloc(40);header.writeUInt32BE(0x10000,0);header.writeUInt16BE(1,4);header.write("head",12);header.writeUInt32BE(1000,20);header.writeUInt32BE(100,24);await writeFile(font,header);await expect(probeMedia(font,loadConfig(process.env))).rejects.toThrow(/exceed/);}finally{await rm(root,{recursive:true,force:true});}});
const integration=process.env.RUN_FFMPEG_INTEGRATION==="1"?it:it.skip;
integration("imported font survives source removal and renders styled captions identically across range caches",async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),"studio-caption-font-"));try{
  const system=[path.join(process.env.WINDIR??"C:\\Windows","Fonts","arial.ttf"),"/System/Library/Fonts/Supplemental/Arial.ttf","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"].find(existsSync);expect(system).toBeDefined();
  const font=path.join(root,"Imported.ttf");await copyFile(system!,font);const store=await ProjectStore.create(path.join(root,"project"),"Fonts"),config=loadConfig({...process.env,VIDEO_STUDIO_DATA_DIR:root,VIDEO_STUDIO_SCRATCH_DIR:path.join(root,"scratch")});
  await store.replace(0,project=>{project.settings.raster={width:320,height:180};project.settings.fps={numerator:10,denominator:1};},{sequences:[],tracks:[],clips:[],media:[],animations:[],generatedArtifacts:[]});
  const imported=await importMedia(store,font,"managed",1,config);expect(imported.asset.media.kind).toBe("font");await rm(font);
  const project=await store.read(),sequence=project.sequences[0]!,track=sequence.tracks.find(track=>track.type==="caption")!,cues=parseCaptions("1\n00:00:00,000 --> 00:00:01,000\nPortable type\n","srt",track.id,project.settings.fps,{fontMediaId:imported.asset.media.id,fontFamily:"Imported",fontSize:24,color:"#ff0000",background:"#00000000",outlineColor:"#ffffff",outlineWidth:1,shadowColor:"#00ff00",shadowOffset:2,marginLeft:20,marginVertical:20,position:"top",align:"left"});
  await store.mutate(2,[{type:"caption.add",sequenceId:sequence.id,caption:cues[0]!}]);expect(sequenceDependencies(await store.read(),sequence.id).media.has(imported.asset.media.id)).toBe(true);
  const render=async(name:string,ranges:number)=>{const output=path.join(root,name+".mkv");const result=await renderSequence(store,config,{sequenceId:sequence.id,presetId:"archive-ffv1",outputPath:output,videoRangeFrames:ranges});const raw=output+".rgba";await runChecked(config.ffmpegPath,["-hide_banner","-y","-i",output,"-map","0:v:0","-pix_fmt","rgba","-f","rawvideo",raw]);return{result,bytes:await readFile(raw)};};
  const whole=await render("whole",0),ranged=await render("ranged",5);expect(whole.bytes.length).toBe(10*320*180*4);expect(ranged.bytes.equals(whole.bytes)).toBe(true);let red=0,green=0;for(let i=0;i<320*180*4;i+=4){if(whole.bytes[i]!>100&&whole.bytes[i+1]!<80)red++;if(whole.bytes[i+1]!>100&&whole.bytes[i]!<80)green++;}expect(red).toBeGreaterThan(50);expect(green).toBeGreaterThan(10);
  await expect(store.mutate(3,[{type:"caption.update",sequenceId:sequence.id,captionId:cues[0]!.id,patch:{style:{...cues[0]!.style,fontMediaId:"missing"}}}])).rejects.toThrow(/imported font/);expect((await store.read()).revision).toBe(3);
 }finally{await rm(root,{recursive:true,force:true});}
},60000);
