import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {it,expect} from 'vitest';
import {defaultClip,secondsToTicks} from '@mcp-video-studio/contracts';import {ProjectStore} from '@mcp-video-studio/core';import {loadConfig,importMedia,runChecked,mediaPath} from '@mcp-video-studio/media';import {renderSequence} from '@mcp-video-studio/renderer';import {exportProjectArchive,importProjectArchive} from '../packages/server/src/archive.js';
const integration=process.env.RUN_FFMPEG_INTEGRATION==='1'?it:it.skip;
const cube=(invert:boolean)=>'LUT_3D_SIZE 2\n'+Array.from({length:8},(_,i)=>[i%2,Math.floor(i/2)%2,Math.floor(i/4)].map(n=>invert?1-n:n).join(' ')).join('\n')+'\n';
integration('managed LUT changes actual pixels consistently across whole/range/nested renders, archive relocation and source cache invalidation',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'studio-lut-render-')),config=loadConfig({...process.env,VIDEO_STUDIO_DATA_DIR:root,VIDEO_STUDIO_SCRATCH_DIR:path.join(root,'scratch')}),store=await ProjectStore.create(path.join(root,'project'),'Managed colors');
 try{
  await store.replace(0,p=>{p.settings.raster={width:64,height:36};p.settings.fps={numerator:4,denominator:1};},{sequences:[],tracks:[],clips:[],media:[],animations:[],generatedArtifacts:[]});
  const file=path.join(root,'invert.cube');await writeFile(file,cube(true));await expect(importMedia(store,file,'linked',1,config)).rejects.toThrow(/managed/);const imported=await importMedia(store,file,'managed',1,config),lut=imported.asset.media;expect(lut.kind).toBe('lut');
  let project=await store.read();const seq=project.sequences[0]!,clip=defaultClip(seq.tracks.find(t=>t.type==='video')!.id,{type:'color',color:'#ff0000'},'LUT color',secondsToTicks(2));clip.effects=[{id:'cube-effect',type:'lut3d',enabled:true,version:1,parameters:{mediaId:lut.id,interpolation:'tetrahedral'}}];await store.mutate(project.revision,[{type:'clip.add',sequenceId:seq.id,clip,mode:'overwrite'}]);
  const decode=async(file:string)=>{const raw=file+'.rgb';await runChecked(config.ffmpegPath,['-hide_banner','-y','-i',file,'-map','0:v:0','-pix_fmt','rgb24','-f','rawvideo',raw]);return readFile(raw);};
  const render=async(target:ProjectStore,name:string,sequenceId=seq.id,frames=0)=>{const output=path.join(root,name+'.mkv');const receipt=await renderSequence(target,config,{sequenceId,presetId:'archive-ffv1',outputPath:output,videoRangeFrames:frames});return{pixels:await decode(output),receipt:{...receipt,sourceHashes:receipt.sourceHashes as Record<string,string>,videoRanges:receipt.videoRanges as Array<{cacheHit:boolean}>}};};
  const whole=await render(store,'whole'),ranged=await render(store,'ranged',seq.id,4);expect(whole.pixels.length).toBe(64*36*3*8);expect(ranged.pixels.equals(whole.pixels),'whole/range pixels').toBe(true);expect(whole.pixels[0]).toBeLessThan(10);expect(whole.pixels[1]).toBeGreaterThan(240);expect(whole.pixels[2]).toBeGreaterThan(240);expect(whole.receipt.sourceHashes).toHaveProperty(lut.id,lut.storage.sha256);
  project=await store.read();const child=project.sequences[0]!,parent=structuredClone(child);parent.id='lut-parent';parent.name='Nested LUT';parent.tracks=parent.tracks.map(track=>({...track,id:'parent-'+track.id,sequenceId:parent.id}));parent.clips=[defaultClip(parent.tracks.find(t=>t.type==='video')!.id,{type:'sequence',sequenceId:seq.id},'Nested colors',secondsToTicks(2))];parent.transitions=[];parent.captions=[];await store.replace(project.revision,p=>{p.sequences.push(parent);},{sequences:[parent.id],tracks:[],clips:[],media:[],animations:[],generatedArtifacts:[]});
  const nested=await render(store,'nested',parent.id,4);expect(nested.pixels.length).toBe(whole.pixels.length);expect(Math.max(...nested.pixels.map((v,i)=>Math.abs(v-whole.pixels[i]!))),'one additional nested RGB/YUV roundtrip stays within3 of255').toBeLessThanOrEqual(3);expect(nested.receipt.sourceHashes).toHaveProperty(lut.id,lut.storage.sha256);
  const archive=path.join(root,'project.mcpstudio');await exportProjectArchive(store.root,archive,(await store.read()).revision);const restored=path.join(root,'relocated');await importProjectArchive(archive,restored);const moved=await render(new ProjectStore(restored),'relocated',parent.id,4);expect(moved.pixels.equals(nested.pixels),'relocated nested pixels').toBe(true);
  await writeFile(mediaPath(store,lut),cube(false));const changed=await render(store,'changed',seq.id,4);expect(changed.pixels[0]).toBeGreaterThan(240);expect(changed.pixels[1]).toBeLessThan(10);expect(changed.pixels[2]).toBeLessThan(10);expect(changed.receipt.sourceHashes[lut.id]).not.toBe(lut.storage.sha256);expect((changed.receipt.videoRanges as Array<{cacheHit:boolean}>).every(range=>!range.cacheHit)).toBe(true);const nestedChanged=await render(store,'nested-changed',parent.id,4);expect(Math.max(...nestedChanged.pixels.map((v,i)=>Math.abs(v-changed.pixels[i]!)))).toBeLessThanOrEqual(3);
  const prior=path.join(root,'historical.mkv');await writeFile(prior,'existing delivery');await expect(renderSequence(store,config,{sequenceId:parent.id,presetId:'archive-ffv1',outputPath:prior,expectedSourceHashes:nested.receipt.sourceHashes})).rejects.toThrow(/differs/);expect(await readFile(prior,'utf8')).toBe('existing delivery');
  await writeFile(mediaPath(store,lut),'LUT_3D_SIZE 999999999\n');await expect(render(store,'hostile',seq.id,4)).rejects.toThrow(/sizes/);
  project=await store.read();await expect(store.mutate(project.revision,[{type:'clip.update',sequenceId:seq.id,clipId:clip.id,patch:{effects:[{...clip.effects[0]!,parameters:{mediaId:lut.id,file:'/etc/passwd'}}]}}])).rejects.toThrow(/requires/);
 }finally{await rm(root,{recursive:true,force:true});}
},120000);
