import {mkdtemp,rm} from "node:fs/promises";import path from "node:path";import os from "node:os";import {expect,it} from "vitest";import {chromium} from "patchright";import axe from "axe-core";
import {Client} from "@modelcontextprotocol/client";import {StdioClientTransport} from "@modelcontextprotocol/client/stdio";import type {StudioProject} from "@mcp-video-studio/contracts";
const integration=process.env.RUN_BROWSER_INTEGRATION==="1"?it:it.skip;
integration("human and MCP create, switch and reuse sequences with durable revisions and accessible controls",async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),"studio-sequences-")),client=new Client({name:"sequence-workflow",version:"1"},{versionNegotiation:{mode:"auto"}});
 const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve("dist/index.js"),"--stdio"],env:{...Object.fromEntries(Object.entries(process.env).filter((p):p is[string,string]=>typeof p[1]==="string")),VIDEO_STUDIO_DATA_DIR:root,VIDEO_STUDIO_GATEWAY_PORT:"0"},stderr:"pipe"});
 const browser=await chromium.launch({headless:true});try{
  await client.connect(transport);const response=await client.callTool({name:"open_studio",arguments:{}}),url=(response.structuredContent as{studioUrl:string}).studioUrl;
  const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(10000);await page.goto(url);await page.getByLabel("Name",{exact:true}).fill("Sequence production");await page.getByRole("button",{name:"Create project",exact:true}).click();
  const open=()=>page.getByRole("button",{name:"Editing workflows",exact:true}).click(),close=()=>page.getByRole("button",{name:"Close editing workflows",exact:true}).click();
  await open();await page.getByLabel("New sequence name",{exact:true}).fill("Scene B");await page.getByRole("button",{name:"Create sequence",exact:true}).click();await page.waitForFunction(()=>document.body.textContent?.includes("rev 1"));expect(await page.getByLabel("Current sequence").locator("option:checked").textContent()).toBe("Scene B");await close();
  await page.getByRole("button",{name:"Color",exact:true}).click();await page.waitForFunction(()=>document.body.textContent?.includes("rev 2"));
  await open();await page.getByLabel("Current sequence").selectOption({label:"Main sequence"});await page.waitForFunction(()=>document.body.textContent?.includes("rev 3"));await page.getByLabel("Reusable source sequence").selectOption({label:"Scene B"});await page.getByRole("button",{name:"Insert sequence at playhead",exact:true}).click();await page.waitForFunction(()=>document.body.textContent?.includes("rev 4"));
  await page.evaluate(axe.source,undefined,false);const accessibility=await page.evaluate(async()=>await(window as unknown as{axe:typeof axe}).axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}}),undefined,false);expect(accessibility.violations.map(item=>({id:item.id,nodes:item.nodes.map(node=>node.target)}))).toEqual([]);await close();
  const state=await page.evaluate(async()=>{const headers={authorization:"Bearer "+sessionStorage.getItem("mcp-video-studio:access")},list=await fetch("/api/projects",{headers}).then(r=>r.json()) as {projects:Array<{path:string}>},projectPath=list.projects[0]!.path;const data=await fetch("/api/project?projectPath="+encodeURIComponent(projectPath),{headers}).then(r=>r.json()) as{project:StudioProject};return{...data,projectPath};});
  const parent=state.project.sequences.find(sequence=>sequence.name==="Main sequence")!,child=state.project.sequences.find(sequence=>sequence.name==="Scene B")!;expect(parent.clips).toHaveLength(1);expect(parent.clips[0]!.source).toEqual({type:"sequence",sequenceId:child.id});expect(state.project.activeSequenceId).toBe(parent.id);
  await page.reload();await page.getByText("Project loaded",{exact:true}).waitFor();expect(await page.locator(".timeline-clip").count()).toBe(1);
  const created=await client.callTool({name:"create_sequence",arguments:{projectPath:state.projectPath,expectedRevision:4,name:"Agent sequence",activate:false}});expect(created.isError).not.toBe(true);
  const inserted=await client.callTool({name:"insert_nested_sequence",arguments:{projectPath:state.projectPath,expectedRevision:5,sequenceId:parent.id,sourceSequenceId:child.id,trackId:parent.tracks[0]!.id,startTick:parent.clips[0]!.durationTick}});expect(inserted.isError).not.toBe(true);
  const stale=await client.callTool({name:"create_sequence",arguments:{projectPath:state.projectPath,expectedRevision:4,name:"Stale",activate:false}});expect(stale.isError).toBe(true);
  const loaded=await client.callTool({name:"get_project",arguments:{projectPath:state.projectPath}}),project=(loaded.structuredContent as{project:StudioProject}).project;expect(project.revision).toBe(6);expect(project.activeSequenceId).toBe(parent.id);expect(project.sequences.find(sequence=>sequence.id===parent.id)!.clips).toHaveLength(2);expect(project.sequences.some(sequence=>sequence.name==="Agent sequence")).toBe(true);
 }finally{await browser.close();await client.close();await rm(root,{recursive:true,force:true});}
},60000);
