import React,{useEffect,useRef,useState} from "react";
import {defaultTransform,framesToTicks,ticksToFrames,type AnimationDocument,type AnimationNode,type AnimationOperation,type ProjectCommand,type Rational,type Transform} from "@mcp-video-studio/contracts";
import {evaluateAnimation} from "../../animation/src/evaluate.js";
import {createAnimationPainter,type AnimationHitRegion} from "../../animation/src/painter.js";
const nodeTypes=["group","text","rect","ellipse","line","path","image","video","camera","particles"] as const;
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange(value:number):void;min?:number;max?:number}){
 return <label>{label}<input type="number" key={String(value)} defaultValue={value} min={min} max={max} step="any" onBlur={event=>{const next=event.currentTarget.valueAsNumber;if(Number.isFinite(next)&&(min===undefined||next>=min)&&(max===undefined||next<=max)&&next!==value)onChange(next);else event.currentTarget.value=String(value);}}/></label>;
}
export function AnimationEditor({animation,fps,onMutate}:{animation:AnimationDocument;fps:Rational;onMutate(commands:ProjectCommand[]):Promise<void>}){
 const [selected,setSelected]=useState(animation.nodes[0]?.id??""),[frame,setFrame]=useState(0),[newType,setNewType]=useState<AnimationNode["type"]>("rect"),[error,setError]=useState("");
 const canvas=useRef<HTMLCanvasElement>(null),regions=useRef<AnimationHitRegion[]>([]),paint=useRef<ReturnType<typeof createAnimationPainter>|null>(null),generation=useRef(0),pending=useRef(Promise.resolve());
 const node=animation.nodes.find(item=>item.id===selected)??animation.nodes[0],frames=Math.ceil(ticksToFrames(animation.durationTick,fps,"ceil")),tick=framesToTicks(Math.min(frame,Math.max(0,frames-1)),fps);
 useEffect(()=>{const request=++generation.current;pending.current=pending.current.catch(()=>undefined).then(async()=>{if(request!==generation.current||!canvas.current)return;paint.current??=createAnimationPainter(canvas.current);try{regions.current=await paint.current(evaluateAnimation(animation,tick),{...animation.canvas,seed:animation.seed,time:tick/35280000});setError("");}catch(caught){setError(caught instanceof Error?caught.message:String(caught));}});},[animation,tick]);
 const update=(patch:Partial<Pick<AnimationNode,"name"|"properties"|"transform">>&{parentId?:string|null})=>{if(node)void onMutate([{type:"animation.node.update",animationId:animation.id,nodeId:node.id,patch}]);};
 const property=(name:string,value:unknown)=>{if(node)update({properties:{...node.properties,[name]:value}});};
 const transform=(patch:Partial<Transform>)=>{if(node)update({transform:{...node.transform,...patch}});};
 const depth=(item:AnimationNode)=>{let level=1,parent=item.parentId;const seen=new Set<string>();while(parent&&!seen.has(parent)){seen.add(parent);level++;parent=animation.nodes.find(n=>n.id===parent)?.parentId;}return level;};
 const descendants=new Set(node?[node.id]:[]);for(let i=0;i<animation.nodes.length;i++)for(const candidate of animation.nodes)if(candidate.parentId&&descendants.has(candidate.parentId))descendants.add(candidate.id);
 const add=()=>{
  const id=crypto.randomUUID(),properties:Record<string,unknown>=newType==="path"?{path:"M 0 0 L 100 0 L 100 100 L 0 100 Z",width:100,height:100,fill:"#ffffff"}:newType==="text"?{text:"New text",fontSize:48,fill:"#ffffff"}:newType==="group"?{}:newType==="camera"?{zoom:1}:newType==="particles"?{count:100,lifetime:2,size:3,speed:60,fill:"#ffffff"}:{width:100,height:100,fill:"#ffffff"};
  if(newType==="image"||newType==="video"){setError("Choose an image or video file below to add an asset object.");return;}
  void onMutate([{type:"animation.node.add",animationId:animation.id,node:{id,type:newType,name:newType,properties,transform:{...defaultTransform(),position:newType==="camera"||newType==="group"?[0,0]:[animation.canvas.width/2,animation.canvas.height/2]}}}]).then(()=>setSelected(id));
 };
 const upload=(file:File|undefined)=>{if(!file)return;if(file.size>9*1024*1024){setError("Animation assets are limited to 9 MiB before base64 encoding.");return;}const reader=new FileReader();reader.onerror=()=>setError("Could not read the selected asset.");reader.onload=()=>{const id=crypto.randomUUID(),type=file.type.startsWith("video/")?"video":"image";void onMutate([{type:"animation.node.add",animationId:animation.id,node:{id,type,name:file.name,properties:{src:String(reader.result),width:animation.canvas.width/2,height:animation.canvas.height/2},transform:{...defaultTransform(),position:[animation.canvas.width/2,animation.canvas.height/2]}}}]).then(()=>setSelected(id));};reader.readAsDataURL(file);};
 return <fieldset className="animation-editor"><legend>Animation objects and keyframes</legend>
  <canvas ref={canvas} aria-label="Animation canvas; click an object or use arrow keys to move the selected object" tabIndex={0} style={{width:"100%",height:"auto",background:"#222",border:"1px solid #666"}} onPointerDown={event=>{const rect=event.currentTarget.getBoundingClientRect(),x=(event.clientX-rect.left)*animation.canvas.width/rect.width,y=(event.clientY-rect.top)*animation.canvas.height/rect.height;const hit=[...regions.current].reverse().find(region=>x>=region.x&&x<=region.x+region.width&&y>=region.y&&y<=region.y+region.height);if(hit)setSelected(hit.id);}} onKeyDown={event=>{if(!node||!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key))return;event.preventDefault();event.stopPropagation();const amount=event.shiftKey?10:1,position=[...node.transform.position] as [number,number];position[event.key==="ArrowLeft"||event.key==="ArrowRight"?0:1]+=event.key==="ArrowLeft"||event.key==="ArrowUp"?-amount:amount;transform({position});}}/>
  <label>Animation frame<input type="range" min={0} max={Math.max(0,frames-1)} value={Math.min(frame,Math.max(0,frames-1))} onChange={event=>setFrame(Number(event.currentTarget.value))}/><output>{frame} / {Math.max(0,frames-1)}</output></label>
  {error&&<p role="alert">{error}</p>}
  <div role="tree" aria-label="Animation hierarchy">{animation.nodes.map((item,index)=><button type="button" role="treeitem" key={item.id} aria-selected={node?.id===item.id} aria-level={depth(item)} aria-expanded={item.type==="group"?true:undefined} tabIndex={node?.id===item.id?0:-1} style={{display:"block",paddingInlineStart:depth(item)*12,color:"#f5f7ff",background:node?.id===item.id?"#304e82":"#172338",border:"1px solid #52647f"}} onClick={()=>setSelected(item.id)} onKeyDown={event=>{let next:AnimationNode|undefined;if(event.key==="ArrowDown")next=animation.nodes[index+1];if(event.key==="ArrowUp")next=animation.nodes[index-1];if(event.key==="ArrowLeft")next=animation.nodes.find(n=>n.id===item.parentId);if(event.key==="ArrowRight")next=animation.nodes.find(n=>n.parentId===item.id);if(next){event.preventDefault();event.stopPropagation();setSelected(next.id);const target=event.currentTarget.parentElement?.children[animation.nodes.indexOf(next)] as HTMLElement|undefined;target?.focus();}}}>{item.name} ({item.type})</button>)}</div>
  <label>New object type<select value={newType} onChange={event=>setNewType(event.currentTarget.value as AnimationNode["type"])}>{nodeTypes.map(type=><option key={type}>{type}</option>)}</select></label><button type="button" onClick={add}>Add animation object</button><label>Add embedded image or video<input type="file" accept="image/png,image/jpeg,image/webp,video/mp4,video/webm" onChange={event=>upload(event.currentTarget.files?.[0])}/></label>
  {node&&<><label>Object name<input key={node.id+node.name} defaultValue={node.name} onBlur={event=>{if(event.currentTarget.value.trim()&&event.currentTarget.value!==node.name)update({name:event.currentTarget.value});}}/></label>
  <label>Parent group<select value={node.parentId??""} onChange={event=>update({parentId:event.currentTarget.value||null})}><option value="">Scene root</option>{animation.nodes.filter(n=>n.type==="group"&&!descendants.has(n.id)).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label>
  <div className="field-pair">{[0,1].map(axis=><NumberField key={axis} label={axis===0?"Object X":"Object Y"} value={node.transform.position[axis]!} onChange={value=>{const position=[...node.transform.position] as [number,number];position[axis]=value;transform({position});}}/>)}</div>
  <div className="field-pair">{[0,1].map(axis=><NumberField key={axis} label={axis===0?"Object scale X":"Object scale Y"} value={node.transform.scale[axis]!} min={0} onChange={value=>{const scale=[...node.transform.scale] as [number,number];scale[axis]=value;transform({scale});}}/>)}</div>
  <NumberField label="Object rotation" value={node.transform.rotation} onChange={rotation=>transform({rotation})}/><NumberField label="Object opacity" min={0} max={1} value={node.transform.opacity} onChange={opacity=>transform({opacity})}/>
  {["rect","ellipse","path","image","video","group"].includes(node.type)&&<div className="field-pair"><NumberField label="Object width" value={Number(node.properties.width??100)} min={0} onChange={value=>property("width",value)}/><NumberField label="Object height" value={Number(node.properties.height??100)} min={0} onChange={value=>property("height",value)}/></div>}
  {node.type==="text"&&<><label>Object text<textarea key={node.id+String(node.properties.text)} defaultValue={String(node.properties.text??"")} onBlur={event=>property("text",event.currentTarget.value)}/></label><NumberField label="Object font size" value={Number(node.properties.fontSize??64)} min={1} onChange={value=>property("fontSize",value)}/></>}
  {node.type==="path"&&<label>SVG path<textarea key={node.id+String(node.properties.path??node.properties.d)} defaultValue={String(node.properties.path??node.properties.d??"")} onBlur={event=>property("path",event.currentTarget.value)}/></label>}
  {node.type==="camera"&&<><NumberField label="Camera zoom" value={Number(node.properties.zoom??1)} min={.001} onChange={value=>property("zoom",value)}/><label><input type="checkbox" checked={node.properties.active!==false} onChange={event=>property("active",event.currentTarget.checked)}/>Active camera</label></>}
  {node.type==="particles"&&<>{[["count",100],["lifetime",2],["size",3],["speed",60],["gravity",0]].map(([key,value])=><NumberField key={String(key)} label={"Particle "+key} value={Number(node.properties[String(key)]??value)} min={0} max={key==="count"?5000:100000} onChange={next=>property(String(key),next)}/>)}</>}
  {!["group","camera","image","video"].includes(node.type)&&<label>Object fill<input type="color" value={/^#[0-9a-f]{6}$/i.test(String(node.properties.fill))?String(node.properties.fill):"#ffffff"} onChange={event=>property("fill",event.currentTarget.value)}/></label>}
  <button type="button" onClick={()=>void onMutate([{type:"animation.node.remove",animationId:animation.id,nodeId:node.id,cascade:true}])}>Remove object and its children</button>
  <OperationEditor key={JSON.stringify(node)+":"+animation.operations.map(operation=>JSON.stringify(operation)).join("|")} animation={animation} node={node} tick={tick} fps={fps} onMutate={onMutate}/></>}
 </fieldset>;
}
function OperationEditor({animation,node,tick,fps,onMutate}:{animation:AnimationDocument;node:AnimationNode;tick:number;fps:Rational;onMutate(commands:ProjectCommand[]):Promise<void>}){
 const owned=animation.operations.filter(operation=>operation.targetId===node.id),[selected,setSelected]=useState(""),existing=owned.find(operation=>operation.id===selected);
 return <fieldset><legend>Object operations / keyframes</legend><label>Operation<select aria-label="Operation" value={selected} onChange={event=>setSelected(event.currentTarget.value)}><option value="">New operation at displayed frame</option>{owned.map(operation=><option key={operation.id} value={operation.id}>{operation.type} at frame {ticksToFrames(operation.startTick,fps,"round")}</option>)}</select></label>
  <OperationForm key={existing?.id??"new:"+tick} animation={animation} node={node} tick={tick} fps={fps} existing={existing} onMutate={onMutate}/>
  {existing&&<><button type="button" onClick={()=>void onMutate([{type:"animation.operation.remove",animationId:animation.id,operationId:existing.id}])}>Remove operation</button><button type="button" disabled={animation.operations.indexOf(existing)===0} onClick={()=>{const ids=animation.operations.map(operation=>operation.id),index=ids.indexOf(existing.id);[ids[index-1],ids[index]]=[ids[index]!,ids[index-1]!];void onMutate([{type:"animation.operations.reorder",animationId:animation.id,operationIds:ids}]);}}>Move operation earlier in equal-time order</button></>}
 </fieldset>;
}
function OperationForm({animation,node,tick,fps,existing,onMutate}:{animation:AnimationDocument;node:AnimationNode;tick:number;fps:Rational;existing:AnimationOperation|undefined;onMutate(commands:ProjectCommand[]):Promise<void>}){
 const [type,setType]=useState<AnimationOperation["type"]>(existing?.type??"transform"),[start,setStart]=useState(ticksToFrames(existing?.startTick??tick,fps,"round")),[duration,setDuration]=useState(ticksToFrames(existing?.durationTick??Math.min(animation.durationTick-tick,35280000),fps,"round")),[easing,setEasing]=useState<AnimationOperation["easing"]>(existing?.easing??"linear"),[parameters,setParameters]=useState<Record<string,unknown>>(existing?.parameters??{to:{position:[...node.transform.position]}});
 const parameter=(name:string,value:unknown)=>setParameters(current=>({...current,[name]:value}));
 const defaults=(kind:AnimationOperation["type"]):Record<string,unknown>=>kind==="transform"?{to:{...node.transform}}:kind==="morph"?{from:node.properties.path??node.properties.d??"",to:node.properties.path??node.properties.d??""}:kind==="fade"?{from:1,to:0}:kind==="scale"?{to:[1,1]}:kind==="rotate"?{to:0}:kind==="moveAlongPath"?{points:[[...node.transform.position],[node.transform.position[0]+100,node.transform.position[1]]]}:kind==="property"?{property:"width",from:Number(node.properties.width??100),to:200}:{};
 const target=parameters.to&&typeof parameters.to==="object"&&!Array.isArray(parameters.to)?parameters.to as Partial<Transform>:{},position=target.position??node.transform.position;
 const submit=()=>{const operation:AnimationOperation={id:existing?.id??crypto.randomUUID(),type,targetId:node.id,startTick:framesToTicks(start,fps),durationTick:framesToTicks(duration,fps),easing,parameters};void onMutate([existing?{type:"animation.operation.update",animationId:animation.id,operationId:existing.id,patch:operation}:{type:"animation.operation.add",animationId:animation.id,operation}]);};
 return <><label>Operation type<select value={type} onChange={event=>{const kind=event.currentTarget.value as AnimationOperation["type"];setType(kind);setParameters(defaults(kind));}}>{["create","write","fade","transform","moveAlongPath","rotate","scale","morph","property","wait"].filter(kind=>kind!=="morph"||node.type==="path").map(kind=><option key={kind}>{kind}</option>)}</select></label>
 <NumberField label="Keyframe start frame" value={start} min={0} onChange={value=>setStart(Math.round(value))}/><NumberField label="Keyframe duration frames" value={duration} min={0} onChange={value=>setDuration(Math.round(value))}/>
 <label>Keyframe easing<select value={easing} onChange={event=>setEasing(event.currentTarget.value as AnimationOperation["easing"])}>{["hold","linear","easeIn","easeOut","easeInOut","easeOutExpo","easeOutBack"].map(value=><option key={value}>{value}</option>)}</select></label>
 {type==="transform"&&<>{[0,1].map(axis=><NumberField key={axis} label={axis===0?"Target X":"Target Y"} value={position[axis]!} onChange={value=>{const next=[...position] as [number,number];next[axis]=value;parameter("to",{...target,position:next});}}/>)}<NumberField label="Target rotation" value={target.rotation??node.transform.rotation} onChange={rotation=>parameter("to",{...target,rotation})}/></>}
 {(type==="fade"||type==="rotate")&&<><NumberField label="From value" value={Number(parameters.from??(type==="fade"?1:node.transform.rotation))} onChange={value=>parameter("from",value)}/><NumberField label="To value" value={Number(parameters.to??0)} onChange={value=>parameter("to",value)}/></>}
 {type==="scale"&&<>{[0,1].map(axis=><NumberField key={axis} label={axis===0?"Target scale X":"Target scale Y"} value={Array.isArray(parameters.to)?Number(parameters.to[axis]):1} min={0} onChange={value=>{const next=Array.isArray(parameters.to)?[...parameters.to]:[1,1];next[axis]=value;parameter("to",next);}}/>)}</>}
 {type==="morph"&&<><label>From SVG path<textarea value={String(parameters.from??"")} onChange={event=>parameter("from",event.currentTarget.value)}/></label><label>To SVG path<textarea value={String(parameters.to??"")} onChange={event=>parameter("to",event.currentTarget.value)}/></label></>}
 {type==="property"&&<><label>Animated property<select value={String(parameters.property??"width")} onChange={event=>{const name=event.currentTarget.value;setParameters({property:name,from:node.properties[name]??(name==="fill"||name==="stroke"?"#ffffff":0),to:name==="fill"||name==="stroke"?"#ff0000":100});}}>{["width","height","fontSize","strokeWidth","zoom","size","fill","stroke"].map(key=><option key={key}>{key}</option>)}</select></label>{["from","to"].map(key=>parameters.property==="fill"||parameters.property==="stroke"?<label key={key}>{key} color<input type="color" value={String(parameters[key]??"#ffffff")} onChange={event=>parameter(key,event.currentTarget.value)}/></label>:<NumberField key={key} label={key+" property value"} value={Number(parameters[key]??0)} onChange={value=>parameter(key,value)}/>)}</>}
 {type==="moveAlongPath"&&<>{(parameters.points as number[][]??[]).map((point,index)=><div className="field-pair" key={index}>{[0,1].map(axis=><NumberField key={axis} label={"Path point "+(index+1)+(axis===0?" X":" Y")} value={point[axis]??0} onChange={value=>{const points=(parameters.points as number[][]).map(item=>[...item]);points[index]![axis]=value;parameter("points",points);}}/>)}</div>)}<button type="button" onClick={()=>parameter("points",[...(parameters.points as number[][]??[]),[...node.transform.position]])}>Add path point</button></>}
 <button type="button" disabled={!Number.isSafeInteger(start)||!Number.isSafeInteger(duration)||start<0||duration<0||framesToTicks(start+duration,fps)>animation.durationTick} onClick={submit}>{existing?"Save operation":"Add operation"}</button></>;
}
