import React,{useState} from "react";
import {defaultTrack,defaultClip,framesToTicks,ticksToFrames,type StudioProject,type Sequence,type ProjectCommand} from "@mcp-video-studio/contracts";
export function SequenceTools({project,sequence,playhead,onMutate}:{project:StudioProject;sequence:Sequence;playhead:number;onMutate(commands:ProjectCommand[]):Promise<void>}){
 const [name,setName]=useState("New sequence"),[sourceId,setSourceId]=useState("");
 const source=project.sequences.find(item=>item.id===sourceId),track=sequence.tracks.find(item=>(item.type==="video"||item.type==="overlay")&&!item.locked);
 const sourceDuration=source?Math.max(0,...source.clips.filter(clip=>clip.enabled).map(clip=>clip.startTick+clip.durationTick),...source.captions.map(caption=>caption.startTick+caption.durationTick)):0;
 const create=()=>{const id=crypto.randomUUID(),created:Sequence={id,name:name.trim(),tracks:[defaultTrack(id,"video",0),defaultTrack(id,"audio",1),defaultTrack(id,"caption",2,"Captions")],clips:[],transitions:[],automation:[],markers:[],captions:[]};void onMutate([{type:"sequence.add",sequence:created},{type:"sequence.activate",sequenceId:id}]);};
 const insert=()=>{if(!source||!track||!sourceDuration)return;const clip=defaultClip(track.id,{type:"sequence",sequenceId:source.id},source.name,framesToTicks(ticksToFrames(sourceDuration,project.settings.fps,"ceil"),project.settings.fps));clip.startTick=framesToTicks(ticksToFrames(playhead,project.settings.fps,"round"),project.settings.fps);void onMutate([{type:"clip.add",sequenceId:sequence.id,clip,mode:"insert"}]);};
 const referenced=project.sequences.some(owner=>owner.clips.some(clip=>clip.source.type==="sequence"&&clip.source.sequenceId===sequence.id))||project.generatedArtifacts.some(artifact=>artifact.scope.sequenceId===sequence.id);
 return <fieldset><legend>Sequences</legend><label>Current sequence<select aria-label="Current sequence" value={sequence.id} onChange={event=>void onMutate([{type:"sequence.activate",sequenceId:event.currentTarget.value}])}>{project.sequences.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
 <label>New sequence name<input value={name} maxLength={200} onChange={event=>setName(event.currentTarget.value)}/></label><button type="button" disabled={!name.trim()} onClick={create}>Create sequence</button>
 <label>Sequence name<input key={sequence.id+sequence.name} defaultValue={sequence.name} maxLength={200} onBlur={event=>{if(event.currentTarget.value.trim()&&event.currentTarget.value.trim()!==sequence.name)void onMutate([{type:"sequence.rename",sequenceId:sequence.id,name:event.currentTarget.value}]);}}/></label>
 <label>Reusable source sequence<select aria-label="Reusable source sequence" value={sourceId} onChange={event=>setSourceId(event.currentTarget.value)}><option value="">Choose a sequence</option>{project.sequences.filter(item=>item.id!==sequence.id).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
 <button type="button" disabled={!sourceDuration||!track||source?.id===sequence.id} onClick={insert}>Insert sequence at playhead</button><p className="hint">Nested clips reuse their source sequence, including its audio. Changes to that source update every use. Insert shifts existing timeline content.</p>
 <button type="button" disabled={project.sequences.length===1||referenced} onClick={()=>void onMutate([{type:"sequence.remove",sequenceId:sequence.id}])}>Remove current sequence</button>{referenced&&<p className="hint">Remove nested or generated references before deleting this sequence.</p>}
 </fieldset>;
}
